//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMDiversity.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVMDiversity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean Data ähnelt.
        /// </summary>
        internal static string Actions_Clean {
            get {
                return ResourceManager.GetString("Actions_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose actions to upload or download data.
        ///When you&apos;re finished, press the &apos;Save&apos; button. ähnelt.
        /// </summary>
        internal static string Actions_Description {
            get {
                return ResourceManager.GetString("Actions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string Actions_GeneralHeader {
            get {
                return ResourceManager.GetString("Actions_GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google Maps ähnelt.
        /// </summary>
        internal static string Actions_GoogleMaps {
            get {
                return ResourceManager.GetString("Actions_GoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maps ähnelt.
        /// </summary>
        internal static string Actions_MapsHeader {
            get {
                return ResourceManager.GetString("Actions_MapsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Actions_NextText {
            get {
                return ResourceManager.GetString("Actions_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Actions_PreviousText {
            get {
                return ResourceManager.GetString("Actions_PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Primary Data ähnelt.
        /// </summary>
        internal static string Actions_PrimaryData {
            get {
                return ResourceManager.GetString("Actions_PrimaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get PropertyNames ähnelt.
        /// </summary>
        internal static string Actions_PropertyNames {
            get {
                return ResourceManager.GetString("Actions_PropertyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Taxon Definitions ähnelt.
        /// </summary>
        internal static string Actions_TaxonDefinitions {
            get {
                return ResourceManager.GetString("Actions_TaxonDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Step: Execute actions ähnelt.
        /// </summary>
        internal static string Actions_Title {
            get {
                return ResourceManager.GetString("Actions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload Data ähnelt.
        /// </summary>
        internal static string Actions_UploadData {
            get {
                return ResourceManager.GetString("Actions_UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Connect {
            get {
                return ResourceManager.GetString("ConnectionsPage_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Connected {
            get {
                return ResourceManager.GetString("ConnectionsPage_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial Taxonomic Catalog: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_DefinitionsCatalog {
            get {
                return ResourceManager.GetString("ConnectionsPage_DefinitionsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To synchronize data, it is necessary to login to the repository and the Mobile DB.
        ///Please fill in your Logindata and connect to the databases. ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Description {
            get {
                return ResourceManager.GetString("ConnectionsPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Disconnect {
            get {
                return ResourceManager.GetString("ConnectionsPage_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnected ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionsPage_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MobileDB-Connection ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileHeader {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of MobileDB: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileLocation {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of TaxonNamesDB: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileTaxLocation {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileTaxLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string ConnectionsPage_NextText {
            get {
                return ResourceManager.GetString("ConnectionsPage_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial Catalog: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryCatalog {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository-Connection ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryHeader {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryName {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryPassword {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryUser {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Step: Establish connections ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose the project you want to edit in the list below: ähnelt.
        /// </summary>
        internal static string ProjectSelection_Description {
            get {
                return ResourceManager.GetString("ProjectSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string ProjectSelection_NextText {
            get {
                return ResourceManager.GetString("ProjectSelection_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string ProjectSelection_PreviousText {
            get {
                return ResourceManager.GetString("ProjectSelection_PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project-Selection ähnelt.
        /// </summary>
        internal static string ProjectSelection_ProjectsHeader {
            get {
                return ResourceManager.GetString("ProjectSelection_ProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Description ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedDescription {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Selection ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedHeader {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Name ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedName {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Step: Choose your Project ähnelt.
        /// </summary>
        internal static string ProjectSelection_Title {
            get {
                return ResourceManager.GetString("ProjectSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual Selection ähnelt.
        /// </summary>
        internal static string SelectFD_ActualSelection {
            get {
                return ResourceManager.GetString("SelectFD_ActualSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&amp;gt; ähnelt.
        /// </summary>
        internal static string SelectFD_AddToSelection {
            get {
                return ResourceManager.GetString("SelectFD_AddToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please configure your search: ähnelt.
        /// </summary>
        internal static string SelectFD_Criteria {
            get {
                return ResourceManager.GetString("SelectFD_ConfigureSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be Patient. ähnelt.
        /// </summary>
        internal static string SelectFD_Description {
            get {
                return ResourceManager.GetString("SelectFD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Selection ähnelt.
        /// </summary>
        internal static string SelectFD_Next {
            get {
                return ResourceManager.GetString("SelectFD_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string SelectFD_Previous {
            get {
                return ResourceManager.GetString("SelectFD_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query Database ähnelt.
        /// </summary>
        internal static string SelectFD_QueryDataBase {
            get {
                return ResourceManager.GetString("SelectFD_QueryDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;lt;-- ähnelt.
        /// </summary>
        internal static string SelectFD_RemoveFromSelection {
            get {
                return ResourceManager.GetString("SelectFD_RemoveFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Restriction_Description {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Date Range ähnelt.
        /// </summary>
        internal static string Restriction_EndDate {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Identification ähnelt.
        /// </summary>
        internal static string Restriction_LastIdent {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_LastIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Updated ähnelt.
        /// </summary>
        internal static string Restriction_LogUpdated {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_LogUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Series Code ähnelt.
        /// </summary>
        internal static string Restriction_SeriesCode {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_SeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Date Range ähnelt.
        /// </summary>
        internal static string Restriction_StartDate {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Group ähnelt.
        /// </summary>
        internal static string Restriction_TaxGroup {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_TaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit Description ähnelt.
        /// </summary>
        internal static string Restriction_UnitDesc {
            get {
                return ResourceManager.GetString("SelectFD_Restriction_UnitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string SelectFD_Result {
            get {
                return ResourceManager.GetString("SelectFD_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string SelectFD_SearchHeader {
            get {
                return ResourceManager.GetString("SelectFD_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collection Event Series ähnelt.
        /// </summary>
        internal static string SearchType_CES {
            get {
                return ResourceManager.GetString("SelectFD_SearchType_CES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification Unit ähnelt.
        /// </summary>
        internal static string SearchType_IU {
            get {
                return ResourceManager.GetString("SelectFD_SearchType_IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling Plot ähnelt.
        /// </summary>
        internal static string SearchType_SP {
            get {
                return ResourceManager.GetString("SelectFD_SearchType_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string SelectFD_SelectAll {
            get {
                return ResourceManager.GetString("SelectFD_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select your SearchType ähnelt.
        /// </summary>
        internal static string SelectFD_SelectSearchType {
            get {
                return ResourceManager.GetString("SelectFD_SelectSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filling Result List ähnelt.
        /// </summary>
        internal static string SelectFD_Status_FillingResults {
            get {
                return ResourceManager.GetString("SelectFD_Status_FillingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querying Database ähnelt.
        /// </summary>
        internal static string SelectFD_Status_Querying {
            get {
                return ResourceManager.GetString("SelectFD_Status_Querying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Field Data for Download ähnelt.
        /// </summary>
        internal static string SelectFD_Title {
            get {
                return ResourceManager.GetString("SelectFD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the SyncMobile Client ähnelt.
        /// </summary>
        internal static string Splash_Line1 {
            get {
                return ResourceManager.GetString("Splash_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die please wait while application is starting... ähnelt.
        /// </summary>
        internal static string Splash_Line2 {
            get {
                return ResourceManager.GetString("Splash_Line2", resourceCulture);
            }
        }
    }
}
