//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMDiversity.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVMDiversity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean Data ähnelt.
        /// </summary>
        internal static string Actions_Clean {
            get {
                return ResourceManager.GetString("Actions_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleaning Database ähnelt.
        /// </summary>
        internal static string Actions_Cleaning_DB {
            get {
                return ResourceManager.GetString("Actions_Cleaning_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose actions to upload or download data.
        ///When you&apos;re finished, press the &apos;Save&apos; button. ähnelt.
        /// </summary>
        internal static string Actions_Description {
            get {
                return ResourceManager.GetString("Actions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string Actions_Done {
            get {
                return ResourceManager.GetString("Actions_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this persists, please consult the Log for further details ähnelt.
        /// </summary>
        internal static string Actions_Error_Advice {
            get {
                return ResourceManager.GetString("Actions_Error_Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to get Property Names ähnelt.
        /// </summary>
        internal static string Actions_Error_PropertyNamesHeader {
            get {
                return ResourceManager.GetString("Actions_Error_PropertyNamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to Upload data! ähnelt.
        /// </summary>
        internal static string Actions_Error_UploadHeader {
            get {
                return ResourceManager.GetString("Actions_Error_UploadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string Actions_GeneralHeader {
            get {
                return ResourceManager.GetString("Actions_GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google Maps ähnelt.
        /// </summary>
        internal static string Actions_GoogleMaps {
            get {
                return ResourceManager.GetString("Actions_GoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maps ähnelt.
        /// </summary>
        internal static string Actions_MapsHeader {
            get {
                return ResourceManager.GetString("Actions_MapsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp; Close ähnelt.
        /// </summary>
        internal static string Actions_NextText {
            get {
                return ResourceManager.GetString("Actions_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Actions_PreviousText {
            get {
                return ResourceManager.GetString("Actions_PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Primary Data ähnelt.
        /// </summary>
        internal static string Actions_PrimaryData {
            get {
                return ResourceManager.GetString("Actions_PrimaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get PropertyNames ähnelt.
        /// </summary>
        internal static string Actions_PropertyNames {
            get {
                return ResourceManager.GetString("Actions_PropertyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to clean your mobile Databases.
        ///All data that has not been uploaded to the remote Database will be LOST!
        ///Do you really want to proceed? ähnelt.
        /// </summary>
        internal static string Actions_ReallyClean_Message {
            get {
                return ResourceManager.GetString("Actions_ReallyClean_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Taxon Definitions ähnelt.
        /// </summary>
        internal static string Actions_TaxonDefinitions {
            get {
                return ResourceManager.GetString("Actions_TaxonDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Step: Execute actions ähnelt.
        /// </summary>
        internal static string Actions_Title {
            get {
                return ResourceManager.GetString("Actions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload Data ähnelt.
        /// </summary>
        internal static string Actions_UploadData {
            get {
                return ResourceManager.GetString("Actions_UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Connect {
            get {
                return ResourceManager.GetString("ConnectionsPage_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Connected {
            get {
                return ResourceManager.GetString("ConnectionsPage_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to establish a connection to the repository. Please check your user name and Password. If you do not already have Credentials you can obtain them from Markus Weiss. ähnelt.
        /// </summary>
        internal static string ConnectionsPage_ConnectionFailed_Content {
            get {
                return ResourceManager.GetString("ConnectionsPage_ConnectionFailed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository Connection Failed ähnelt.
        /// </summary>
        internal static string ConnectionsPage_ConnectionFailed_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_ConnectionFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t create database working copies. Please check the paths of your mobile databases and try again. ähnelt.
        /// </summary>
        internal static string ConnectionsPage_CreateWorkingCopies_Description {
            get {
                return ResourceManager.GetString("ConnectionsPage_CreateWorkingCopies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failure ähnelt.
        /// </summary>
        internal static string ConnectionsPage_CreateWorkingCopies_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_CreateWorkingCopies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial Taxonomic Catalog: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_DefinitionsCatalog {
            get {
                return ResourceManager.GetString("ConnectionsPage_DefinitionsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To synchronize data, it is necessary to login to the repository and the Mobile DB.
        ///Please fill in your Logindata and connect to the databases. ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Description {
            get {
                return ResourceManager.GetString("ConnectionsPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Disconnect {
            get {
                return ResourceManager.GetString("ConnectionsPage_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnected ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionsPage_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading necessary Definitions... ähnelt.
        /// </summary>
        internal static string ConnectionsPage_LoadingDefinitions {
            get {
                return ResourceManager.GetString("ConnectionsPage_LoadingDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MobileDB-Connection ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileHeader {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of MobileDB: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileLocation {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of TaxonNamesDB: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_MobileTaxLocation {
            get {
                return ResourceManager.GetString("ConnectionsPage_MobileTaxLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string ConnectionsPage_NextText {
            get {
                return ResourceManager.GetString("ConnectionsPage_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are trying to connect to a repository that is different from then one associated with your mobile database. 
        ///Do you want to clean the mobile database now and associate it with the new repository?
        ///ATTENTION: All data in your mobile database will be LOST! ähnelt.
        /// </summary>
        internal static string ConnectionsPage_NonHomeDB_Content {
            get {
                return ResourceManager.GetString("ConnectionsPage_NonHomeDB_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non-HomeDB connection ähnelt.
        /// </summary>
        internal static string ConnectionsPage_NonHomeDB_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_NonHomeDB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial Catalog: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryCatalog {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository-Connection ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryHeader {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryName {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryPassword {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username: ähnelt.
        /// </summary>
        internal static string ConnectionsPage_RepositoryUser {
            get {
                return ResourceManager.GetString("ConnectionsPage_RepositoryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Last Session wasn&apos;t closed properly. Do you want to reopen that session? Otherwise all unsaved changes you made will be lost! ähnelt.
        /// </summary>
        internal static string ConnectionsPage_ResumeSession_Description {
            get {
                return ResourceManager.GetString("ConnectionsPage_ResumeSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resume last Session? ähnelt.
        /// </summary>
        internal static string ConnectionsPage_ResumeSession_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_ResumeSession_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Step: Establish connections ähnelt.
        /// </summary>
        internal static string ConnectionsPage_Title {
            get {
                return ResourceManager.GetString("ConnectionsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        /// </summary>
        internal static string Control_DateRange_From {
            get {
                return ResourceManager.GetString("Control_DateRange_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Until ähnelt.
        /// </summary>
        internal static string Control_DateRange_To {
            get {
                return ResourceManager.GetString("Control_DateRange_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string MainWindow_Cancel {
            get {
                return ResourceManager.GetString("MainWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ? ähnelt.
        /// </summary>
        internal static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string MainWindow_Menu_Program {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string MainWindow_Menu_Program_Options {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diversity Mobile - SyncMobile Client ähnelt.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to save maps that will later be available on your mobile device. ähnelt.
        /// </summary>
        internal static string Map_Description {
            get {
                return ResourceManager.GetString("Map_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Screen Size ähnelt.
        /// </summary>
        internal static string Map_DeviceScreenSize {
            get {
                return ResourceManager.GetString("Map_DeviceScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File description ähnelt.
        /// </summary>
        internal static string Map_FileDescription {
            get {
                return ResourceManager.GetString("Map_FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string Map_FileHeader {
            get {
                return ResourceManager.GetString("Map_FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        internal static string Map_FileName {
            get {
                return ResourceManager.GetString("Map_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;-- Map ähnelt.
        /// </summary>
        internal static string Map_FromMap {
            get {
                return ResourceManager.GetString("Map_FromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        internal static string Map_Height {
            get {
                return ResourceManager.GetString("Map_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        internal static string Map_Latitude {
            get {
                return ResourceManager.GetString("Map_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        internal static string Map_Longitude {
            get {
                return ResourceManager.GetString("Map_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Map ähnelt.
        /// </summary>
        internal static string Map_Next {
            get {
                return ResourceManager.GetString("Map_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        internal static string Map_Position {
            get {
                return ResourceManager.GetString("Map_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Map_Previous {
            get {
                return ResourceManager.GetString("Map_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map successfully saved! ähnelt.
        /// </summary>
        internal static string Map_Saved {
            get {
                return ResourceManager.GetString("Map_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Map ähnelt.
        /// </summary>
        internal static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; Map ähnelt.
        /// </summary>
        internal static string Map_ToMap {
            get {
                return ResourceManager.GetString("Map_ToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        internal static string Map_Width {
            get {
                return ResourceManager.GetString("Map_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string Options_Browse {
            get {
                return ResourceManager.GetString("Options_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Options_Cancel {
            get {
                return ResourceManager.GetString("Options_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository Connection ähnelt.
        /// </summary>
        internal static string Options_Connection_Header {
            get {
                return ResourceManager.GetString("Options_Connection_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field Database ähnelt.
        /// </summary>
        internal static string Options_DataCatalog {
            get {
                return ResourceManager.GetString("Options_DataCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database Server ähnelt.
        /// </summary>
        internal static string Options_DBServer {
            get {
                return ResourceManager.GetString("Options_DBServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field Data ähnelt.
        /// </summary>
        internal static string Options_FieldData {
            get {
                return ResourceManager.GetString("Options_FieldData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maps ähnelt.
        /// </summary>
        internal static string Options_Maps_Header {
            get {
                return ResourceManager.GetString("Options_Maps_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobile ähnelt.
        /// </summary>
        internal static string Options_Mobile_Header {
            get {
                return ResourceManager.GetString("Options_Mobile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobile Database ähnelt.
        /// </summary>
        internal static string Options_MobileDB {
            get {
                return ResourceManager.GetString("Options_MobileDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobile Taxa ähnelt.
        /// </summary>
        internal static string Options_MobileTaxa {
            get {
                return ResourceManager.GetString("Options_MobileTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Options_Save {
            get {
                return ResourceManager.GetString("Options_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screen Height ähnelt.
        /// </summary>
        internal static string Options_ScreenHeight {
            get {
                return ResourceManager.GetString("Options_ScreenHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screen Width ähnelt.
        /// </summary>
        internal static string Options_ScreenWidth {
            get {
                return ResourceManager.GetString("Options_ScreenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Password ähnelt.
        /// </summary>
        internal static string Options_ShowPassword {
            get {
                return ResourceManager.GetString("Options_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Sql Authentication ähnelt.
        /// </summary>
        internal static string Options_SqlAuth {
            get {
                return ResourceManager.GetString("Options_SqlAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxon Database ähnelt.
        /// </summary>
        internal static string Options_TaxonCatalog {
            get {
                return ResourceManager.GetString("Options_TaxonCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Truncate Data Items ähnelt.
        /// </summary>
        internal static string Options_TruncateDataItems {
            get {
                return ResourceManager.GetString("Options_TruncateDataItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Device Dimensions ähnelt.
        /// </summary>
        internal static string Options_UseDeviceDimensions {
            get {
                return ResourceManager.GetString("Options_UseDeviceDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name ähnelt.
        /// </summary>
        internal static string Options_Username {
            get {
                return ResourceManager.GetString("Options_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose the project you want to edit in the list below: ähnelt.
        /// </summary>
        internal static string ProjectSelection_Description {
            get {
                return ResourceManager.GetString("ProjectSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string ProjectSelection_NextText {
            get {
                return ResourceManager.GetString("ProjectSelection_NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string ProjectSelection_PreviousText {
            get {
                return ResourceManager.GetString("ProjectSelection_PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project-Selection ähnelt.
        /// </summary>
        internal static string ProjectSelection_ProjectsHeader {
            get {
                return ResourceManager.GetString("ProjectSelection_ProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Description ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedDescription {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Selection ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedHeader {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Name ähnelt.
        /// </summary>
        internal static string ProjectSelection_SelectedName {
            get {
                return ResourceManager.GetString("ProjectSelection_SelectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Step: Choose your Project ähnelt.
        /// </summary>
        internal static string ProjectSelection_Title {
            get {
                return ResourceManager.GetString("ProjectSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Restriction_Description {
            get {
                return ResourceManager.GetString("Restriction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Date Range ähnelt.
        /// </summary>
        internal static string Restriction_EndDate {
            get {
                return ResourceManager.GetString("Restriction_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Identification ähnelt.
        /// </summary>
        internal static string Restriction_LastIdent {
            get {
                return ResourceManager.GetString("Restriction_LastIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Updated ähnelt.
        /// </summary>
        internal static string Restriction_LogUpdated {
            get {
                return ResourceManager.GetString("Restriction_LogUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Series Code ähnelt.
        /// </summary>
        internal static string Restriction_SeriesCode {
            get {
                return ResourceManager.GetString("Restriction_SeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Date Range ähnelt.
        /// </summary>
        internal static string Restriction_StartDate {
            get {
                return ResourceManager.GetString("Restriction_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Group ähnelt.
        /// </summary>
        internal static string Restriction_TaxGroup {
            get {
                return ResourceManager.GetString("Restriction_TaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit Description ähnelt.
        /// </summary>
        internal static string Restriction_UnitDesc {
            get {
                return ResourceManager.GetString("Restriction_UnitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collection Event Series ähnelt.
        /// </summary>
        internal static string SearchType_CES {
            get {
                return ResourceManager.GetString("SearchType_CES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification Unit ähnelt.
        /// </summary>
        internal static string SearchType_IU {
            get {
                return ResourceManager.GetString("SearchType_IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling Plot ähnelt.
        /// </summary>
        internal static string SearchType_SP {
            get {
                return ResourceManager.GetString("SearchType_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual Selection ähnelt.
        /// </summary>
        internal static string SelectFD_ActualSelection {
            get {
                return ResourceManager.GetString("SelectFD_ActualSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --&gt; ähnelt.
        /// </summary>
        internal static string SelectFD_AddToSelection {
            get {
                return ResourceManager.GetString("SelectFD_AddToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Criteria ähnelt.
        /// </summary>
        internal static string SelectFD_Criteria {
            get {
                return ResourceManager.GetString("SelectFD_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be Patient. ähnelt.
        /// </summary>
        internal static string SelectFD_Description {
            get {
                return ResourceManager.GetString("SelectFD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Selection ähnelt.
        /// </summary>
        internal static string SelectFD_Next {
            get {
                return ResourceManager.GetString("SelectFD_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string SelectFD_Previous {
            get {
                return ResourceManager.GetString("SelectFD_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query Database ähnelt.
        /// </summary>
        internal static string SelectFD_QueryDataBase {
            get {
                return ResourceManager.GetString("SelectFD_QueryDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query Result ähnelt.
        /// </summary>
        internal static string SelectFD_QueryResult {
            get {
                return ResourceManager.GetString("SelectFD_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;-- ähnelt.
        /// </summary>
        internal static string SelectFD_RemoveFromSelection {
            get {
                return ResourceManager.GetString("SelectFD_RemoveFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string SelectFD_SearchHeader {
            get {
                return ResourceManager.GetString("SelectFD_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string SelectFD_SelectAll {
            get {
                return ResourceManager.GetString("SelectFD_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select your SearchType ähnelt.
        /// </summary>
        internal static string SelectFD_SelectSearchType {
            get {
                return ResourceManager.GetString("SelectFD_SelectSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filling Result List ähnelt.
        /// </summary>
        internal static string SelectFD_Status_FillingResults {
            get {
                return ResourceManager.GetString("SelectFD_Status_FillingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Field Data for Download ähnelt.
        /// </summary>
        internal static string SelectFD_Title {
            get {
                return ResourceManager.GetString("SelectFD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Truncate Data Items ähnelt.
        /// </summary>
        internal static string SelectFD_Truncate {
            get {
                return ResourceManager.GetString("SelectFD_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excludes the child items of the ones you selected from the download. ähnelt.
        /// </summary>
        internal static string SelectFD_Truncate_ToolTip {
            get {
                return ResourceManager.GetString("SelectFD_Truncate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronize ähnelt.
        /// </summary>
        internal static string Selection_Next {
            get {
                return ResourceManager.GetString("Selection_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Selection_Previous {
            get {
                return ResourceManager.GetString("Selection_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Final Selection ähnelt.
        /// </summary>
        internal static string Selection_SelectionHeader {
            get {
                return ResourceManager.GetString("Selection_SelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm the Selection ähnelt.
        /// </summary>
        internal static string Selection_Title {
            get {
                return ResourceManager.GetString("Selection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading necessary Collection Definitions, please wait. ähnelt.
        /// </summary>
        internal static string Services_Definitions_LoadingCollectionDefinitions {
            get {
                return ResourceManager.GetString("Services_Definitions_LoadingCollectionDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading necessary Properties, please wait. ähnelt.
        /// </summary>
        internal static string Services_Definitions_LoadingProperties {
            get {
                return ResourceManager.GetString("Services_Definitions_LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading Taxon Lists ähnelt.
        /// </summary>
        internal static string Services_Definitions_LoadingTaxa {
            get {
                return ResourceManager.GetString("Services_Definitions_LoadingTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading Field Data ähnelt.
        /// </summary>
        internal static string Services_FieldData_Downloading {
            get {
                return ResourceManager.GetString("Services_FieldData_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querying Database ähnelt.
        /// </summary>
        internal static string Services_FieldData_Querying {
            get {
                return ResourceManager.GetString("Services_FieldData_Querying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading Field Data ähnelt.
        /// </summary>
        internal static string Services_FieldData_Uploading {
            get {
                return ResourceManager.GetString("Services_FieldData_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the SyncMobile Client ähnelt.
        /// </summary>
        internal static string Splash_Line1 {
            get {
                return ResourceManager.GetString("Splash_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die please wait while application is starting... ähnelt.
        /// </summary>
        internal static string Splash_Line2 {
            get {
                return ResourceManager.GetString("Splash_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose which of the available Catalogs will be available on the phone ähnelt.
        /// </summary>
        internal static string Taxon_Description {
            get {
                return ResourceManager.GetString("Taxon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxon List Selection ähnelt.
        /// </summary>
        internal static string Taxon_Header {
            get {
                return ResourceManager.GetString("Taxon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Taxon_Previous {
            get {
                return ResourceManager.GetString("Taxon_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Taxon Data ähnelt.
        /// </summary>
        internal static string Taxon_StartDownload {
            get {
                return ResourceManager.GetString("Taxon_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Taxon data for download ähnelt.
        /// </summary>
        internal static string Taxon_Title {
            get {
                return ResourceManager.GetString("Taxon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The start date of the range must be earlier than its end date. ähnelt.
        /// </summary>
        internal static string Validation_DateRangeRestriction_EndBeforeStart {
            get {
                return ResourceManager.GetString("Validation_DateRangeRestriction_EndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Must be between 100 and 800 ähnelt.
        /// </summary>
        internal static string Validation_Options_FieldDimensionOutOfRange {
            get {
                return ResourceManager.GetString("Validation_Options_FieldDimensionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Field May not be empty ähnelt.
        /// </summary>
        internal static string Validation_Options_FieldEmpty {
            get {
                return ResourceManager.GetString("Validation_Options_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected file does not exist. ähnelt.
        /// </summary>
        internal static string Validation_Options_FileNotFound {
            get {
                return ResourceManager.GetString("Validation_Options_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to enter a Username if using SQL authentication. ähnelt.
        /// </summary>
        internal static string Validation_Options_UsernameEmpty {
            get {
                return ResourceManager.GetString("Validation_Options_UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The search text may not be empty. ähnelt.
        /// </summary>
        internal static string Validation_TextRestriction_SearchStringEmpty {
            get {
                return ResourceManager.GetString("Validation_TextRestriction_SearchStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string YNDialog_No {
            get {
                return ResourceManager.GetString("YNDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string YNDialog_Yes {
            get {
                return ResourceManager.GetString("YNDialog_Yes", resourceCulture);
            }
        }
    }
}
